[platformio]
src_dir = main
include_dir = main/firmware/include

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv

build_flags =
  -I main/firmware/include
  -I main/core/logging
  -I main/core/menu
  -I main/core/automation
  -I main/core/module_manager
  -I main/core/storage
  -I main/core/events
  -I main/core/status
  -I main/core/registry
  -I main/core/shell
  -I main/core/input
  -I main/core/display
  -I main/core/screens
  -I main/core/ui
  -I main/core/ui_controller
  -I main/core/app_manager
  -I main/apps/system
  -I main/apps/wifi
  -I main/apps/gpio
  -I main/apps/ble
  -I main/apps/logs
  -I main/apps/settings
  -I main/apps/diagnostics
  -I main/apps/uart
  -I main/apps/health