#ifndef BLACKCAPY_H
#define BLACKCAPY_H

#define BLACKCAPY_NAME "BlackCapy"
#define BLACKCAPY_VERSION "0.2.0"
#define BLACKCAPY_AUTHOR "Henrique"

#define BLACKCAPY_SERIAL_BAUD 115200
#define BLACKCAPY_STATUS_LED 2

enum ToolId {
  TOOL_SYSTEM_MONITOR = 1,
  TOOL_WIFI_SCANNER,
  TOOL_GPIO_CONSOLE,
  TOOL_MODULE_MANAGER,
  TOOL_AUTOMATION_ENGINE,
  TOOL_REBOOT
};

#endif
