#ifndef BLACKCAPY_H
#define BLACKCAPY_H

#define BLACKCAPY_NAME "BlackCapy"
#define BLACKCAPY_VERSION "1.0.0"
#define BLACKCAPY_AUTHOR "Henrique"

#define BLACKCAPY_SERIAL_BAUD 115200

enum ToolId {
  TOOL_SYSTEM_MONITOR = 1,
  TOOL_WIFI_SCANNER,
  TOOL_GPIO_CONSOLE,
  TOOL_MODULE_MANAGER,
  TOOL_AUTOMATION_ENGINE,
  TOOL_BLE_SCANNER,
  TOOL_I2C_SCANNER,
  TOOL_BENCHMARK,
  TOOL_LOG_VIEWER,
  TOOL_SETTINGS,
  TOOL_DIAGNOSTICS,
  TOOL_UART_MONITOR,
  TOOL_HEALTH_MONITOR,
  TOOL_WIFI_MONITOR,
  TOOL_PWM_GENERATOR,
  TOOL_ANALOG_READER,
  TOOL_TIMER,
  TOOL_RANDOM,
  TOOL_STORAGE_STATUS,
  TOOL_IR_CONSOLE,
  TOOL_RF_ANALYZER,
  TOOL_SUBGHZ_SCANNER,
  TOOL_RFID_READER,
  TOOL_NFC_READER,
  TOOL_CAN_MONITOR,
  TOOL_GPS_STATUS,
  TOOL_LORA_STATUS,
  TOOL_CAPTURE_VIEWER,
  TOOL_SIGNAL_DATABASE,
  TOOL_AI_ANALYZER,
  TOOL_AI_REPORT_VIEWER,
  TOOL_MODULE_MANIFEST,
  TOOL_MODULE_ID_DIAGNOSTICS,
  TOOL_REBOOT
};

#endif
