[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

src_dir = ..
include_dir = firmware/include

build_flags =
  -I firmware/include
  -I core/logging
  -I core/menu
  -I core/automation
  -I core/module_manager
  -I apps/system
  -I apps/wifi
  -I apps/gpio
